### ISSUE TITLE
Packet Too Big Error Players Unable to Connect to Server

### ISSUE THREAD

**Issue by AsuraTakun** [AllTheMods/ATM-9#114]
When trying to login to my server, players are getting immediately kicked due to an error:
`Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Packet too big (is 11902849, should be less than 8388608): net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket@3b27e8d1`

The first number can vary from player to player but is the same number for that player each time. The errors right before that on the server log are:
```
[17Jul2023 04:28:05.376] [Netty Epoll Server IO #3/WARN] [com.connectivity.Connectivity/]: Packet:ClientboundLevelChunkWithLightPacket caused an error above, printing name & data
[17Jul2023 04:28:07.609] [Netty Epoll Server IO #3/WARN] [com.connectivity.Connectivity/]: Failed to print data for packet
java.lang.StackOverflowError: null
	at java.lang.StringBuffer.append(StringBuffer.java:393) ~[?:?]
	at java.io.StringWriter.write(StringWriter.java:122) ~[?:?]
	at com.google.gson.stream.JsonWriter.string(JsonWriter.java:642) ~[gson-2.10.jar%2372!/:?]
	at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402) ~[gson-2.10.jar%2372!/:?]
	at com.google.gson.stream.JsonWriter.beginObject(JsonWriter.java:311) ~[gson-2.10.jar%2372!/:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:363) ~[gson-2.10.jar%2372!/:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70) ~[gson-2.10.jar%2372!/:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196) ~[gson-2.10.jar%2372!/:?]
```

In which the last 3 lines repeat themselves about 100-200 times, followed by:
```
[17Jul2023 04:28:07.614] [Netty Epoll Server IO #3/ERROR] [net.minecraft.network.PacketEncoder/]: Error receiving packet 36
java.lang.IllegalArgumentException: Packet too big (is 11902849, should be less than 8388608): net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket@3b27e8d1
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:48) ~[server-1.20.1-20230612.114412-srg.jar%23593!/:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[server-1.20.1-20230612.114412-srg.jar%23593!/:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.82.Final.jar%2381!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.82.Final.jar%2381!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.82.Final.jar%2381!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.82.Final.jar%2385!/:4.1.82.Final]
	at net.minecraft.network.Connection.m_243087_(Connection.java:224) ~[server-1.20.1-20230612.114412-srg.jar%23593!/:?]
	at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:213) ~[server-1.20.1-20230612.114412-srg.jar%23593!/:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar%2382!/:4.1.82.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar%2382!/:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar%2382!/:4.1.82.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.82.Final.jar%2386!/:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar%2382!/:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar%2382!/:4.1.82.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Unfortunately, the backups ran overnight and have deleted all the backups from before the issue started occurring. The player who first triggered it thought it might have been EnderIO (primitive alloy smelter), so we tried disabling EnderIO and it did not help. I also tried installing PacketFixer, which just changed the error to a critical failure with Mixin due to not being able to set the packet size change.

I have included the latest and debug, but there is not a crash report.

Server:
[debug.log](https://github.com/AllTheMods/ATM-9/files/12069303/debug.log)
[latest.log](https://github.com/AllTheMods/ATM-9/files/12069304/latest.log)

Client:
[latest.log](https://github.com/AllTheMods/ATM-9/files/12069316/latest.log)

**Comment by AsuraTakun** [comment]
Here is a clean log/debug after upgrading to 0.0.39 if it is helpful at all
[latest.log](https://github.com/AllTheMods/ATM-9/files/12076901/latest.log)
[debug.log](https://github.com/AllTheMods/ATM-9/files/12076902/debug.log)

**Comment by AsuraTakun** [comment]
As an update, I did edit a player pos and had him walk back to base instead of teleporting and he was able to login but then got kicked when near the base.

**Comment by AsuraTakun** [comment]
I was able to tediously isolate this to the Easy Villagers mod. A different player had automated the breeding by sticking a carrot on a botany hopper pot feeding into the villager breeder with an item pipez going out of that into the incubator then pipez from the incubator into a normal chest. Not sure if this was an overflow/leak of some sort or just that the villagers bred the packet too big when they didn't stop breeding when the chest was full.
