### ISSUE TITLE
Crash When Hit by a Wither Skeleton

### ISSUE THREAD

**Issue by soultstice** [AllTheMods/ATM-9#1153]
Any time I get hit by a Wither Skeleton, it dies and I crash. Screenshots of my gear in case it's an enchant or Apotheosis problem. I somewhat recently made it to The Other but I don't remember when this started and didn't have many run-ins with Wither Skeletons up until The Other. There is also two instances of the crash from two different days in case that helps.
![Screenshot 2024-01-09 002612](https://github.com/AllTheMods/ATM-9/assets/95586692/681b7d96-63f0-4148-b26d-e866826388bd)
![Screenshot 2024-01-09 002630](https://github.com/AllTheMods/ATM-9/assets/95586692/74792211-7072-44c0-9dd5-02b8afe1f801)
![Screenshot 2024-01-09 002644](https://github.com/AllTheMods/ATM-9/assets/95586692/9f8b23b8-b932-4e64-ad36-317332ec8872)
![Screenshot 2024-01-09 002701](https://github.com/AllTheMods/ATM-9/assets/95586692/f0c9a156-5cb9-441d-99bc-262be9701016)
[crash-2024-01-09_00.20.14-server.txt](https://github.com/AllTheMods/ATM-9/files/13869395/crash-2024-01-09_00.20.14-server.txt)
[crash-2024-01-07_13.03.35-server.txt](https://github.com/AllTheMods/ATM-9/files/13869396/crash-2024-01-07_13.03.35-server.txt)

**Comment by nailfor** [comment]
Did u have a twilightforest:cloud in your inventory?

**Comment by soultstice** [comment]
Not that I know, I'm not too sure what that even is.

**Comment by LuziferSenpai** [comment]
No it even happens when a Wither Skeleton dies from Thorns while Shooting you.

**Comment by Pixzle** [comment]
In our server, we removed thorns/icy thorns/curse of bones from all our gear and this stopped. Could cheat in a command block to loop wipe wither skeletons on spawn which would allow you to play as normal

**Comment by vorly** [comment]
How are you re-joining the server?  Every time I re-join, the server crashes after this happens. I need to wipe my character data on the server before I can re-join.  I'm hoping it's fixed next patch or there is another more permanent solution besides not using Thorns..

**Comment by BadmojoC** [comment]
Can confirm this is also happening on our ATM 9 server. We ended up using only one piece of gear (vibranium leggins) with Thorns II and the server crashed after a little bit of skeleton beating. The character was in The Other dimension.

@vorly You dont need to wipe the character data. If you have access to the server then just go to your world folder and look for "playerdata" folder. There search for a .dat file of your minecraft account.
- the exact ID of your account can be found here: https://cs.namemc.com/

After you find your .dat file you just open it with NBTexplorer:
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac

There search for the "Pos" row and edit your X Y Z so you teleport your character somewhere else so the skeletons can't hit and crash you. Oh and dont forget to save it :)

**Comment by x13x54** [comment]
Same here, I even got a crash log for y'all!
Confirmed and reproduced by having someone with thorns getting hit by a skelly in a laboratory setting.
They do crash the server again within 5 seconds of logging in again IF nobody else removed the skeleton presence prior to throns-player logging in

> [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source) ~[?:?]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:111) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:760) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2548) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.world.entity.monster.AbstractSkeleton.m_8107_(AbstractSkeleton.java:116) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.server.level.ServerLevel.observable$track(ServerLevel.java:6669) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.server.level.ServerLevel.redirect$bif000$observable$onTickNonPassenger(ServerLevel.java:6685) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23913!/:?]
	... 5 more

**Comment by SpartaWarsec** [comment]
Server version 0.3.0 All The Mods 9
Same issue: the problem is the enchantment  ("Thorn") and a hit from a Wither Skeleton   






[04Aug2024 21:58:17.429] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023) ~[?:?]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:1046) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:111) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:760) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2548) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.monster.AbstractSkeleton.m_8107_(AbstractSkeleton.java:116) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.level.ServerLevel.observable$track(ServerLevel.java:7169) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.level.ServerLevel.redirect$bin000$observable$onTickNonPassenger(ServerLevel.java:7185) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	... 5 more

**Comment by daniele-bondi** [comment]
I also ran into this problem. I think it happens with both skeletons and wither skeletons, cause I crashed once in the other and once in the twilight forest (where there were only normal skeletons).

**Comment by ScorpN21** [comment]
Bug Report: Game Crash When Hit by Wither Skeletons with "Repellent" Enchantment
Modpack Version:
ATM 9 - 0.3.0

Minecraft Version:
1.20.x (Bitte die genaue Version angeben, falls bekannt)

Forge Version:
V. 1.259.1.20166

Description:
The game crashes whenever I am hit by a Wither Skeleton while wearing armor or holding a weapon with the "Repellent" enchantment. This crash occurs consistently and makes it difficult to engage Wither Skeletons without avoiding crashes.

Steps to Reproduce:

Equip any armor piece or weapon with the "Repellent" enchantment.
Enter a Nether Fortress or any location where Wither Skeletons spawn.
Engage in combat with a Wither Skeleton.
Observe the game crash upon being hit by the Wither Skeleton.
Expected Behavior:
The "Repellent" enchantment should trigger its effect without causing the game to crash.



Additional Information:

I have tested this with different armor pieces and weapons, and the crash only occurs when the "Repellent" enchantment is present.
The crash happens specifically with Wither Skeletons; other mobs do not seem to cause this issue.
I have tried removing other mods that might conflict with "Repellent," but the issue persists.

**Comment by marcobsidian** [comment]
> Bug Report: Game Crash When Hit by Wither Skeletons with "Repellent" Enchantment Modpack Version: ATM 9 - 0.3.0
> 
> Minecraft Version: 1.20.x
> 
> Forge Version: V. 1.259.1.20166
> 
> Description: The game crashes whenever I am hit by a Wither Skeleton while wearing armor or holding a weapon with the "Repellent" enchantment. This crash occurs consistently and makes it difficult to engage Wither Skeletons without avoiding crashes.
> 
> Steps to Reproduce:
> 
> Equip any armor piece or weapon with the "Repellent" enchantment. Enter a Nether Fortress or any location where Wither Skeletons spawn. Engage in combat with a Wither Skeleton. Observe the game crash upon being hit by the Wither Skeleton. Expected Behavior: The "Repellent" enchantment should trigger its effect without causing the game to crash.
> 
> Additional Information:
> 
> I have tested this with different armor pieces and weapons, and the crash only occurs when the "Repellent" enchantment is present. The crash happens specifically with Wither Skeletons; other mobs do not seem to cause this issue. I have tried removing other mods that might conflict with "Repellent," but the issue persists.

We are experiencing this issue on a Multiplayer Server rn with noone having the Repellent Enchantment.

**Comment by OlickQC** [comment]
Same issue.
Can we get a fix, please? 

`[30Dec2024 00:57:44.129] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
at net.minecraft.server.MinecraftServer.m5703(MinecraftServer.java:897) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.server.dedicated.DedicatedServer.m5703(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.server.MinecraftServer.m5705(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.server.MinecraftServer.m130011(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.server.MinecraftServer.m206580(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.util.ConcurrentModificationException
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023) ~[?:?]
at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:1046) ~[?:?]
at net.minecraft.world.entity.ai.goal.GoalSelector.m186081(GoalSelector.java:118) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.world.entity.ai.goal.GoalSelector.m25373(GoalSelector.java:111) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.world.entity.Mob.m6140(Mob.java:760) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.world.entity.LivingEntity.m8107(LivingEntity.java:2548) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.world.entity.Mob.m8107(Mob.java:536) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.world.entity.monster.Monster.m8107(Monster.java:42) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.world.entity.monster.AbstractSkeleton.m8107(AbstractSkeleton.java:116) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.world.entity.LivingEntity.m8119(LivingEntity.java:2298) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.world.entity.Mob.m8119(Mob.java:337) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.world.entity.monster.Skeleton.m8119(Skeleton.java:73) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.server.level.ServerLevel.observable$track(ServerLevel.java:10169) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.server.level.ServerLevel.redirect$cpp000$observable$onTickNonPassenger(ServerLevel.java:10185) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.server.level.ServerLevel.m8647(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.world.level.Level.m46653(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.server.level.ServerLevel.m184063(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.world.level.entity.EntityTickList.m156910(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.server.level.ServerLevel.m8793(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
at net.minecraft.server.MinecraftServer.m5703(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%231017!/:?]
shit just fucking crash for nothing`
