### ISSUE TITLE
Server doesn't start anymore

### ISSUE THREAD

**Issue by qawasx** [AllTheMods/ATM-9#1538]
### Possible Fixes

Yes

### Modpack Version

0.2.54

### What happened?

I crafted a honeycomb block from honeycombs and clicked the little x in the refined storage grid to put the rest of the honeycombs back into the grid, then the server crashed.
This is the error i get in the console: 
[26Mar2024 10:53:52.313] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
com.google.gson.JsonIOException: java.io.IOException: No space left on device
	at com.google.gson.Gson.toJson(Gson.java:932) ~[gson-2.10.jar%2372!/:?]
	at com.google.gson.Gson.toJson(Gson.java:863) ~[gson-2.10.jar%2372!/:?]
	at net.minecraft.server.PlayerAdvancements.m_135991_(PlayerAdvancements.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23901!/:?]
	at net.minecraft.server.players.PlayerList.m_6765_(PlayerList.java:340) ~[server-1.20.1-20230612.114412-srg.jar%23901!/:?]
	at net.minecraft.server.players.PlayerList.m_11302_(PlayerList.java:645) ~[server-1.20.1-20230612.114412-srg.jar%23901!/:?]
	at net.minecraft.server.MinecraftServer.m_195514_(MinecraftServer.java:531) ~[server-1.20.1-20230612.114412-srg.jar%23901!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:824) ~[server-1.20.1-20230612.114412-srg.jar%23901!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23901!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23901!/:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

but this is literally not true. i have space on the device. what can i do here?

### Crash Log

https://gist.github.com/qawasx/262fb454155b6d703ea4fe5d38cd3a5b

**Comment by NarrikSynthfox** [comment]
How much space do you have left though is the question?

**Comment by qawasx** [comment]
This is hosted through a server hoster site, according to their metrics i have 48GB left

**Comment by qawasx** [comment]
The hoster site purged my advancements folder and now it works again. question is, if it stops working again if i gain the same amount of advancements
