### ISSUE TITLE
[Crash]: Frequent server crashes due to "Ticking entity" issue

### ISSUE THREAD

**Issue by KNaiFen** [AllTheMods/ATM-9#1551]
### Possible Fixes

Yes

### Modpack Version

0.2.54

### What happened?

Advance note: I installed other mods, two about adding more planes and a drop cleanup mod, which I don't think will have an impact on the AI convenience.

My server has been up for four days now, and since yesterday, the server has started crashing frequently because of this error, and looking at the logs I think it's a problem with the monster AI, but I can't pinpoint the exact reason why.
It even crashed four times in a row in the early hours of this morning

This is the log error:
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756) ~[?:?]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:778) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2548) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.monster.AbstractSkeleton.m_8107_(AbstractSkeleton.java:116) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.level.ServerLevel.observable$track(ServerLevel.java:7169) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.level.ServerLevel.redirect$bib000$observable$onTickNonPassenger(ServerLevel.java:7185) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23911!/:?]
	... 5 more
	
The following four error reports are basically very similar, all because of a single error and then the server immediately crashed:
[crash-2024-03-29_01.19.07-server.txt](https://github.com/AllTheMods/ATM-9/files/14796578/crash-2024-03-29_01.19.07-server.txt)
[crash-2024-03-29_01.26.25-server.txt](https://github.com/AllTheMods/ATM-9/files/14796581/crash-2024-03-29_01.26.25-server.txt)
[crash-2024-03-29_07.19.29-server.txt](https://github.com/AllTheMods/ATM-9/files/14796582/crash-2024-03-29_07.19.29-server.txt)
[crash-2024-03-29_07.44.13-server.txt](https://github.com/AllTheMods/ATM-9/files/14796583/crash-2024-03-29_07.44.13-server.txt)
[log--2024-03-29_01.19.07.log](https://github.com/AllTheMods/ATM-9/files/14796584/log--2024-03-29_01.19.07.log)
[log-2024-03-29_01.26.25-server.log](https://github.com/AllTheMods/ATM-9/files/14796585/log-2024-03-29_01.26.25-server.log)
[log-2024-03-29_07.19.29-server.log](https://github.com/AllTheMods/ATM-9/files/14796586/log-2024-03-29_07.19.29-server.log)
[log-2024-03-29_07.44.13-server.log](https://github.com/AllTheMods/ATM-9/files/14796587/log-2024-03-29_07.44.13-server.log)

### Crash Log

https://gist.github.com/KNaiFen/72e6252a897e48c04e7c11cf6516711a

### Latest.Log

https://gist.github.com/KNaiFen/d3e244072590addf3c6730660034ab0a

**Comment by James103** [comment]
Were you or any players on your server fighting a Wither Skeleton when the server crashed?

**Comment by KNaiFen** [comment]
Oh actually about an hour after sending out this ISSUE I found the cause and banned the generation of the Wither Skeleton and have never crashed due to this issue again.
As far as I can verify there was no one in the server fighting the Wither Skeleton at the time of the crash, it just got refreshed and stood there and the server had a probability of crashing.
I've encountered a lot of Wither Skeleton in my playthroughs, but there were no crashes then, so I'm guessing that this monster causing the server to crash is a probabilistic event.

**Comment by Possemaster** [comment]
Same issue here on 0.2.56

Keeps crashing on logging in, had to move my character with NBT editor to 0,128,0 in order to fix it.
I was on a pirate ship with a lot of skeletons. As you see below exact same error as OP.

```
[20Apr2024 07:48:20.826] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023) ~[?:?]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:1046) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:111) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:760) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2548) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.monster.AbstractSkeleton.m_8107_(AbstractSkeleton.java:116) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.monster.Skeleton.m_8119_(Skeleton.java:73) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.level.ServerLevel.observable$track(ServerLevel.java:7669) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.level.ServerLevel.redirect$bih000$observable$onTickNonPassenger(ServerLevel.java:7685) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	... 5 more
```

**Comment by Possemaster** [comment]
Another Server crash, Now in the Other Ancient Pyramid. Exact same entity.

```
[20Apr2024 12:57:55.370] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:1023) ~[?:?]
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:1046) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.m_186081_(GoalSelector.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2548) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.monster.AbstractSkeleton.m_8107_(AbstractSkeleton.java:116) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.level.ServerLevel.observable$track(ServerLevel.java:7669) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.level.ServerLevel.redirect$bih000$observable$onTickNonPassenger(ServerLevel.java:7685) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[server-1.20.1-20230612.114412-srg.jar%23905!/:?]
	... 5 more
```

**Comment by Possemaster** [comment]
In the Crash logs it indeed shows the Wither Skeleton as being ticking

```
-- Entity being ticked --
Details:
	Entity Type: minecraft:wither_skeleton (net.minecraft.world.entity.monster.WitherSkeleton)
	Entity ID: 106330
	Entity Name: Wither Skeleton
	Entity's Exact location: 1115.92, 161.00, 0.58
	Entity's Block location: World: (1115,161,0), Section: (at 11,1,0 in 69,10,0; chunk contains blocks 1104,-64,0 to 1119,319,15), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,-64,0 to 1535,319,511)
	Entity's Momentum: -0.38, 0.36, 0.16
	Entity's Passengers: []
	Entity's Vehicle: null

```

**Comment by Possemaster** [comment]
Also normal Skeleton is impacted. Maybe it has something to do with my damage reflects?

-- Entity being ticked --
Details:
	Entity Type: minecraft:skeleton (net.minecraft.world.entity.monster.Skeleton)
	Entity ID: 105070
	Entity Name: Skeleton
	Entity's Exact location: 224.87, 64.00, 70.30
	Entity's Block location: World: (224,64,70), Section: (at 0,0,6 in 14,4,4; chunk contains blocks 224,-64,64 to 239,319,79), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.05, -0.08, 0.07
	Entity's Passengers: []
	Entity's Vehicle: null

**Comment by James103** [comment]
The following assumes you were fighting a Skeleton or Wither Skeleton when the server crashed.
Can you please locate the player data file corresponding to your player data on your server, then zip and attach it in a new comment?
If that is not possible, can you please run `/recipe take @s *` followed by `/data get entity @s`, then post the resulting output?
If that is not possible, can you please take screenshots of all your armor, weapons, and Curios then attach them?

**Comment by Possemaster** [comment]
Hey @James103 I have found the issue for me was the Thorns Pendant Necklace from Artifacts that  cause the issue.
I removed that pendant and could slay 100s of skeletons in the dungeon without issues.
Went in naked with only the pendant and after 4-5 hits from the skeleton the server crashed.
So 100% the pendant cause the issue.

**Comment by James103** [comment]
Do you get a similar crash if you enchant your armor with Thorns then let (Wither) Skeletons attack you and die from that Thorns effect?

**Comment by x13x54** [comment]
Caused by thorns killing skeleton-based mobs, see #1153
