### ISSUE TITLE
[Crash]: When trying to join a world after update from 0.2.35

### ISSUE THREAD

**Issue by TinouHD** [AllTheMods/ATM-9#1568]
### Possible Fixes

Yes

### Modpack Version

0.2.55

### What happened?

The game crashes (client only) after updating from `0.2.35` to `0.2.55`.
I have customize the config of SOL Carrot edition but obviously this is not related to the crash.
Same config on server work perfectly.

```
-- Head --
Thread: Render thread
Suspected Mods: 
	Glodium (glodium), Version: 1.20-1.4-forge
		at TRANSFORMER/glodium@1.20-1.4-forge/com.glodblock.github.glodium.reflect.ReflectKit.readField(ReflectKit.java:60)

	ExtendedAE (expatternprovider), Version: 1.20-1.0.18-forge
		at TRANSFORMER/expatternprovider@1.20-1.0.18-forge/com.glodblock.github.extendedae.util.Ae2ReflectClient.getInscribeRecipe(Ae2ReflectClient.java:68)

	Just Enough Items (jei), Version: 15.3.0.4
		Issue tracker URL: https://github.com/mezz/JustEnoughItems/issues?q=is%3Aissue
		at TRANSFORMER/jei@15.3.0.4/mezz.jei.library.load.PluginLoader.lambda$createRecipeManager$8(PluginLoader.java:123)
```

### Crash Log

https://gist.github.com/TinouHD/f36426e133d2c347ab6efea17f9a3bc2

### Latest.Log

https://gist.github.com/TinouHD/4e1a97925b870fa856549d581a775f05

**Comment by Mitchell5200** [comment]
fixed by downgrading Glodium to 1.3, we'll be doing that pack wide in 0.2.56
