### ISSUE TITLE
[Crash]: Crashing Randomly

### ISSUE THREAD

**Issue by BoloYon** [AllTheMods/ATM-9#1609]
### Possible Fixes

Yes

### Modpack Version

0.2.56

### What happened?

Crashing randomly and I cannot figure out why.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-04-10 22:38:38
Description: Exception in server tick loop

java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?] {}
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?] {re:mixin}
	at net.minecraft.server.level.DistanceManager.m_140805_(DistanceManager.java:119) ~[client-1.20.1-20230612.114412-srg.jar%23988!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_8489_(ServerChunkCache.java:273) ~[client-1.20.1-20230612.114412-srg.jar%23988!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:gtceu.mixins.json:ServerChunkProviderMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:545) ~[client-1.20.1-20230612.114412-srg.jar%23988!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_8466_(ServerChunkCache.java:269) ~[client-1.20.1-20230612.114412-srg.jar%23988!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ChunkLoadDebug,pl:mixin:APP:gtceu.mixins.json:ServerChunkProviderMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ServerChunkCache_CurrentLoadingMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:758) ~[client-1.20.1-20230612.114412-srg.jar%23988!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[client-1.20.1-20230612.114412-srg.jar%23988!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23988!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[client-1.20.1-20230612.114412-srg.jar%23988!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[client-1.20.1-20230612.114412-srg.jar%23988!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23988!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

### Crash Log

https://gist.github.com/BoloYon/8e8433308937635949f3b0d10e6c0a24

**Comment by BoloYon** [comment]
Let me add: This is strictly single player
