### ISSUE TITLE
[0.0.45] EnderIO 存在问题

### ISSUE THREAD

**Issue by Lazy-gyl** [AllTheMods/ATM-9#174]
在Simple Alloy Smelter 中放入铁锭,黑曜石,Coal Powder的时候崩溃报错

Time: 2023-07-30 18:38:30
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "com.enderio.machines.common.io.item.MultiSlotAccess.getAccesses()" is null
	at com.enderio.machines.common.blockentity.AlloySmelterBlockEntity$AlloySmeltingMachineTask.consumeInputs(AlloySmelterBlockEntity.java:241) ~[EnderIO-6.0.6-alpha-all.jar%23513!/:6.0.6-alpha] {re:classloading}
	at com.enderio.machines.common.blockentity.AlloySmelterBlockEntity$AlloySmeltingMachineTask.consumeInputs(AlloySmelterBlockEntity.java:189) ~[EnderIO-6.0.6-alpha-all.jar%23513!/:6.0.6-alpha] {re:classloading}
	at com.enderio.machines.common.blockentity.task.CraftingMachineTask.tick(CraftingMachineTask.java:114) ~[EnderIO-6.0.6-alpha-all.jar%23513!/:6.0.6-alpha] {re:classloading}
	at com.enderio.machines.common.blockentity.task.host.MachineTaskHost.tick(MachineTaskHost.java:104) ~[EnderIO-6.0.6-alpha-all.jar%23513!/:6.0.6-alpha] {re:classloading}
	at com.enderio.machines.common.blockentity.AlloySmelterBlockEntity.serverTick(AlloySmelterBlockEntity.java:120) ~[EnderIO-6.0.6-alpha-all.jar%23513!/:6.0.6-alpha] {re:classloading}
	at com.enderio.machines.common.blockentity.PrimitiveAlloySmelterBlockEntity.serverTick(PrimitiveAlloySmelterBlockEntity.java:91) ~[EnderIO-6.0.6-alpha-all.jar%23513!/:6.0.6-alpha] {re:classloading}
	at com.enderio.core.common.blockentity.EnderBlockEntity.tick(EnderBlockEntity.java:49) ~[EnderIO-6.0.6-alpha-all.jar%23513!/:6.0.6-alpha] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:689) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:782) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:468) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:gtceu-common.mixins.json:LevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:351) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:level_load,re:classloading,pl:accesstransformer:B,xf:fml:libx:level_load,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:corgilib.mixins.json:MixinServerLevel,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

**Comment by Rover656** [comment]
This has been fixed in Ender IO v6.0.8-alpha and up.
