### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by KvikSter1** [AllTheMods/ATM-9#2170]
### Possible Fixes

Yes

### Modpack Version

Forge 1.20.1 ATM 9

### What happened?

I installed the Russian localization and the game stopped running.

[16:48:04] [INIT] KubeJS 2001.6.5-build.16; MC 2001 forge
[16:48:04] [INIT] Loaded plugins:
[16:48:04] [INIT] - dev.latvian.mods.kubejs.forge.BuiltinKubeJSForgePlugin
[16:48:04] [INIT] - dev.latvian.mods.kubejs.forge.BuiltinKubeJSForgeClientPlugin
[16:48:04] [INIT] - com.lowdragmc.lowdraglib.kjs.LDLibKubeJSPlugin
[16:48:04] [INIT] - dev.ftb.mods.ftbxmodcompat.ftbquests.kubejs.KubeJSIntegration
[16:48:04] [INIT] - dev.ftb.mods.ftbxmodcompat.ftbchunks.kubejs.FTBChunksKubeJSPlugin
[16:48:04] [INIT] - dev.ftb.mods.ftbxmodcompat.ftbteams.kubejs.FTBTeamsKubeJSPlugin
[16:48:04] [INIT] - com.gregtechceu.gtceu.integration.kjs.GregTechKubeJSPlugin
[16:48:04] [INIT] - com.tom.createores.kubejs.KubeJSExcavation
[16:48:04] [INIT] - com.almostreliable.morejs.Plugin
[16:48:04] [INIT] - com.blakebr0.cucumber.compat.kubejs.CucumberKubeJSPlugin
[16:48:04] [INIT] - com.almostreliable.ponderjs.PonderJSPlugin
[16:48:05] [INFO] read_json_from_mod.js#5: Loaded Java class 'net.minecraftforge.resource.ResourcePackLoader'
[16:48:05] [INFO] read_json_from_mod.js#8: Loaded Java class 'java.util.stream.Collectors'
[16:48:05] [INFO] read_json_from_mod.js#9: Loaded Java class 'net.minecraft.server.packs.repository.ServerPacksSource'
[16:48:05] [INFO] read_json_from_mod.js#10: Loaded Java class 'net.minecraft.server.packs.resources.FallbackResourceManager'
[16:48:05] [INFO] Loaded script startup_scripts:read_json_from_mod.js in 0.051 s
[16:48:05] [INFO] Loaded script startup_scripts:AE2/Universal_Press.js in 0.002 s
[16:48:05] [INFO] Loaded script startup_scripts:custom_additions.js in 0.001 s
[16:48:05] [INFO] farmingForBlockheads.js#11: Loaded Java class 'net.blay09.mods.farmingforblockheads.api.FarmingForBlockheadsAPI'
[16:48:05] [INFO] Loaded script startup_scripts:farmingForBlockheads.js in 0.003 s
[16:48:05] [INFO] Loaded script startup_scripts:gtceu/alcr.js in 0.002 s
[16:48:05] [INFO] Loaded script startup_scripts:gtceu/apiary.js in 0.003 s
[16:48:05] [INFO] gtceu/greenhouse.js#4: Loaded Java class 'dev.latvian.mods.kubejs.util.Tags'
[16:48:05] [INFO] Loaded script startup_scripts:gtceu/greenhouse.js in 0.002 s
[16:48:05] [INFO] Loaded script startup_scripts:gtceu/gregstar_placeholders.js in 0.0 s
[16:48:05] [INFO] gtceu/material_modification.js#4: Loaded Java class 'com.gregtechceu.gtceu.api.data.chemical.material.properties.FluidProperty'
[16:48:05] [INFO] gtceu/material_modification.js#5: Loaded Java class 'com.gregtechceu.gtceu.api.data.chemical.material.properties.OreProperty'
[16:48:05] [INFO] Loaded script startup_scripts:gtceu/material_modification.js in 0.002 s
[16:48:05] [INFO] gtceu/mega_fusion_reactor.js#4: Loaded Java class 'com.gregtechceu.gtceu.common.machine.multiblock.electric.FusionReactorMachine'
[16:48:05] [INFO] Loaded script startup_scripts:gtceu/mega_fusion_reactor.js in 0.021 s
[16:48:05] [INFO] gtceu/micro_universe_orb.js#4: Loaded Java class 'com.gregtechceu.gtceu.common.machine.multiblock.part.EnergyHatchPartMachine'
[16:48:05] [INFO] gtceu/micro_universe_orb.js#5: Loaded Java class 'com.gregtechceu.gtceu.api.capability.recipe.IO'
[16:48:05] [INFO] Loaded script startup_scripts:gtceu/micro_universe_orb.js in 0.01 s
[16:48:05] [INFO] Loaded script startup_scripts:gtceu/miner.js in 0.001 s
[16:48:05] [INFO] Loaded script startup_scripts:gtceu/starforge.js in 0.001 s
[16:48:05] [INFO] mekanismStartup.js#18: Loaded Java class 'mekanism.api.chemical.slurry.Slurry'
[16:48:05] [INFO] mekanismStartup.js#19: Loaded Java class 'mekanism.api.chemical.slurry.SlurryBuilder'
[16:48:05] [INFO] mekanismStartup.js#20: Loaded Java class 'mekanism.api.chemical.gas.Gas'
[16:48:05] [INFO] mekanismStartup.js#21: Loaded Java class 'mekanism.api.chemical.gas.GasBuilder'
[16:48:05] [INFO] Loaded script startup_scripts:mekanismStartup.js in 0.003 s
[16:48:05] [INFO] Loaded script startup_scripts:mining_dim_layers.js in 0.0 s
[16:48:05] [INFO] mysticalagriculture.js#4: Loaded Java class 'com.blakebr0.mysticalagriculture.api.MysticalAgricultureAPI'
[16:48:05] [INFO] Loaded script startup_scripts:mysticalagriculture.js in 0.001 s
[16:48:05] [INFO] Loaded script startup_scripts:settings.js in 0.002 s
[16:48:05] [INFO] Loaded script startup_scripts:worldgen.js in 0.001 s
[16:48:05] [INFO] Loaded 18/18 KubeJS startup scripts in 0.974 s with 0 errors and 0 warnings
[16:48:06] [ERROR] ! Error in 'GTCEuStartupEvents.registry': FluidProperty cannot be empty!
[16:48:06] [ERROR] ! java.lang.IllegalStateException: FluidProperty cannot be empty!
[16:48:06] [ERROR] !   at com.gregtechceu.gtceu.api.data.chemical.material.properties.FluidProperty.verifyProperty(FluidProperty.java:77)
[16:48:06] [ERROR] !   at com.gregtechceu.gtceu.api.data.chemical.material.properties.MaterialProperties.lambda$verify$0(MaterialProperties.java:72)
[16:48:06] [ERROR] !   at java.util.ArrayList.forEach(ArrayList.java:1511)
[16:48:06] [ERROR] !   at com.gregtechceu.gtceu.api.data.chemical.material.properties.MaterialProperties.verify(MaterialProperties.java:72)
[16:48:06] [ERROR] !   at com.gregtechceu.gtceu.api.data.chemical.material.Material.setProperty(Material.java:506)
[16:48:06] [ERROR] !   at java.lang.reflect.Method.invoke(Method.java:568)
[16:48:06] [ERROR] !   at …rhino.MemberBox.invoke(MemberBox.java:160)
[16:48:06] [ERROR] !   at …rhino.NativeJavaMethod.call(NativeJavaMethod.java:463)
[16:48:06] [ERROR] !   at …rhino.Interpreter.interpretLoop(Interpreter.java:986)
[16:48:06] [ERROR] !   at …rhino.Interpreter.interpret(Interpreter.java:370)
[16:48:06] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:72)
[16:48:06] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[16:48:06] [ERROR] !   at …rhino.Context.doTopCall(Context.java:1307)
[16:48:06] [ERROR] !   at …rhino.InterpretedFunction.call(InterpretedFunction.java:70)
[16:48:06] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[16:48:06] [ERROR] !   at …rhino.ArrowFunction.call(ArrowFunction.java:42)
[16:48:06] [ERROR] !   at …rhino.Context.callSync(Context.java:1290)
[16:48:06] [ERROR] !   at …rhino.InterfaceAdapter.invoke(InterfaceAdapter.java:125)
[16:48:06] [ERROR] !   at …rhino.VMBridge.lambda$newInterfaceProxy$0(VMBridge.java:74)
[16:48:06] [ERROR] !   at TRANSFORMER/jdk.proxy3/jdk.proxy3.$Proxy120.onEvent(Unknown Source)
[16:48:06] [ERROR] !   at …kubejs.event.EventHandlerContainer.handle(EventHandlerContainer.java:39)
[16:48:06] [ERROR] !   at …kubejs.event.EventHandler.postToHandlers(EventHandler.java:304)
[16:48:06] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:264)
[16:48:06] [ERROR] !   at …kubejs.event.EventHandler.post(EventHandler.java:226)
[16:48:06] [ERROR] !   at com.gregtechceu.gtceu.integration.kjs.GTRegistryInfo.postEvent(GTRegistryInfo.java:162)
[16:48:06] [ERROR] !   at com.gregtechceu.gtceu.integration.kjs.GTRegistryInfo.registerFor(GTRegistryInfo.java:167)
[16:48:06] [ERROR] !   at com.gregtechceu.gtceu.common.CommonProxy$KJSEventWrapper.materialRegistry(CommonProxy.java:287)
[16:48:06] [ERROR] !   at com.gregtechceu.gtceu.common.CommonProxy.initMaterials(CommonProxy.java:201)
[16:48:06] [ERROR] !   at com.gregtechceu.gtceu.common.CommonProxy.init(CommonProxy.java:121)
[16:48:06] [ERROR] !   at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
[16:48:06] [ERROR] !   at net.minecraftforge.fml.DeferredWorkQueue.lambda$makeRunnable$2(DeferredWorkQueue.java:81)
[16:48:06] [ERROR] !   at net.minecraftforge.fml.DeferredWorkQueue.makeRunnable(DeferredWorkQueue.java:76)
[16:48:06] [ERROR] !   at net.minecraftforge.fml.DeferredWorkQueue.lambda$runTasks$0(DeferredWorkQueue.java:60)
[16:48:06] [ERROR] !   at java.util.concurrent.ConcurrentLinkedDeque.forEach(ConcurrentLinkedDeque.java:1650)
[16:48:06] [ERROR] !   at net.minecraftforge.fml.DeferredWorkQueue.runTasks(DeferredWorkQueue.java:60)
[16:48:06] [ERROR] !   at net.minecraftforge.fml.core.ParallelTransition.lambda$finalActivityGenerator$2(ParallelTransition.java:35)
[16:48:06] [ERROR] !   at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
[16:48:06] [ERROR] !   at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[16:48:06] [ERROR] !   at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:43)
[16:48:06] [ERROR] !   at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:28)
[16:48:06] [ERROR] !   at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:224)
[16:48:06] [ERROR] !   at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:210)
[16:48:06] [ERROR] !   at java.util.Optional.ifPresent(Optional.java:178)
[16:48:06] [ERROR] !   at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:210)
[16:48:06] [ERROR] !   at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183)
[16:48:06] [ERROR] !   at java.lang.Iterable.forEach(Iterable.java:75)
[16:48:06] [ERROR] !   at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183)
[16:48:06] [ERROR] !   at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:69)
[16:48:06] [ERROR] !   at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:89)
[16:48:06] [ERROR] !   at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:69)
[16:48:06] [ERROR] !   at net.minecraft.client.Minecraft.<init>(Minecraft.java:459)
[16:48:06] [ERROR] !   at net.minecraft.client.main.Main.main(Main.java:182)
[16:48:06] [ERROR] !   at java.lang.reflect.Method.invoke(Method.java:568)
[16:48:06] [ERROR] !   at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.12/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
[16:48:06] [ERROR] !   at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.12/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
[16:48:06] [ERROR] !   at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.12/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
[16:48:06] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
[16:48:06] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[16:48:06] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[16:48:06] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
[16:48:06] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
[16:48:06] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[16:48:06] [ERROR] !   at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[16:48:06] [ERROR] !   at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

### Crash Log

https://gist.github.com/KvikSter1/1ff1723ae80e6c835dcf0c1f1ed04b2a

**Comment by Mitchell5200** [comment]
Latest.log file please, and the actual atm9 pack version number

**Comment by KvikSter1** [comment]
1.20.1-47.3.12 
the last one is the same - https://gist.github.com/KvikSter1/1ff1723ae80e6c835dcf0c1f1ed04b2a

**Comment by Mitchell5200** [comment]
latest.log file from `/logs/`, and that is not the pack version, that is the MC version and forge version

**Comment by Mitchell5200** [comment]
Oh a cracked client, Sorry, we don't support those
