### ISSUE TITLE
Can't install forge 47.0.14

### ISSUE THREAD

**Issue by Seegras** [AllTheMods/ATM-9#28]
It bombs, specifically with 47.0.14
```
Exception caught from launcher
java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:115)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:147)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:29)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Exiting with ERROR
```

Setting it to 47.0.15 or 47.0.16 works (but 47.0.16 has other problems, like some mined blocks vanishing). 

(This is with PrismLauncher on Linux, and no, the official curse launcher does not work on Linux).

**Comment by whatthedrunk** [comment]
Not sure what your issue was but I do know there are reports of forge not wanting to download correctly. New version is on  47.0.19 so you should be good now.
