### ISSUE TITLE
[0.056]SinglePlayer World Hangs

### ISSUE THREAD

**Issue by attardw** [AllTheMods/ATM-9#291]
I have no idea whats causing the issue to be honest, I've tried looking at logs as well as loading up the output console on launch. Everything launches correctly and the world will load. 
Once I get to a specific area the world "hangs" so to speak, I can still walk around, break blocks, place them etc. But the broken blocks don't drop anything, cheat console doesn't work, cant teleport with waypoints, and chunks wont load. 
Attempting to close the game ends with it getting stuck on "Removed all colony views" and requires the instance to be closed with task manager.
I've been able to solve many crashing issues before, but that's because the server would actually crash, and the logs would point to a specific mod causing the issue. From what Ive seen, I couldn't find any direct pointer to a specific mod.

[latest.log](https://github.com/AllTheMods/ATM-9/files/12444212/latest.log)

Some more added information:
1. I have not added any mods to the modpack
2. It is a fresh install as I just started playing a couple days ago
3. every so often while waiting in the hung world, my frames will drop to 0 for a second then return to 60 with the output console reporting ""IO-Worker-65" prio=5 Id=340 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@178ce48e
	at java.base@17.0.3/jdk.internal.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@178ce48e
	at java.base@17.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at java.base@17.0.3/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401)
	at java.base@17.0.3/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122)
	at java.base@17.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.3/java.lang.Thread.run(Thread.java:833)"

Something else I thought I should add is that it is an amplified world, with cities disabled

**Comment by runexheart** [comment]
This also happens on 0.0.57, non amplified world, both old save updated to new pack version and completely new world.
https://mclo.gs/L7zR3P1
