### ISSUE TITLE
ATM 9-0.1.11 Townhall crash the server

### ISSUE THREAD

**Issue by GamerCH** [AllTheMods/ATM-9#502]
My frend created a Townhall and than it crashed instant the Server

Using Builder Wand to place Townhall crashes the Server
Placing without Builder Wand works.

Log:
1/2: https://pastebin.com/DYEufaFb
2/2: https://pastebin.com/L6VwH8HC

Crash:
[19:22:44] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "com.minecolonies.api.colony.IColony.getWorld()" because "colony" is null
        Index: 13
        Listeners:
                0: HIGH
                1: net.minecraftforge.eventbus.EventBus$$Lambda$1475/0x000001478a704d08@1ec4c036
                2: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                3: NORMAL
                4: net.minecraftforge.eventbus.EventBus$$Lambda$1475/0x000001478a704d08@b57278f
                5: ASM: class com.mrcrayfish.furniture.common.mail.PostOffice onTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                6: ASM: class com.tiviacz.travelersbackpack.handlers.ForgeEventHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                7: net.minecraftforge.eventbus.EventBus$$Lambda$1475/0x000001478a704d08@165d5d89
                8: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onServerTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                9: net.minecraftforge.eventbus.EventBus$$Lambda$1475/0x000001478a704d08@6842d2c2
                10: ASM: mods.railcraft.Railcraft@1a8531d1 handleLevelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                11: ASM: class com.ldtteam.structurize.event.EventSubscriber onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                12: ASM: class com.ldtteam.structurize.storage.ServerStructurePackLoader onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                13: ASM: class com.ldtteam.structurize.storage.ServerFutureProcessor onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                14: net.minecraftforge.eventbus.EventBus$$Lambda$1475/0x000001478a704d08@50bf7a8c
                15: ASM: de.melanx.utilitix.content.BetterMending@1867aea0 pullXP(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                16: net.minecraftforge.eventbus.EventBus$$Lambda$1475/0x000001478a704d08@62e6544b
                17: net.minecraftforge.eventbus.EventBus$$Lambda$1475/0x000001478a704d08@1e2bec8b
                18: ASM: me.desht.pneumaticcraft.common.event.MiscEventHandler@60d4ac85 onWorldTickEnd(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                19: ASM: class com.aetherteam.aether.event.listeners.DimensionListener onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                20: ASM: INSTANCE worldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                21: ASM: com.darkere.crashutils.CrashUtils@23d39101 onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                22: ASM: class com.hollingsworth.arsnouveau.api.source.SourceManager serverTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                23: ASM: class com.railwayteam.railways.forge.events.CommonEventsForge onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                24: net.minecraftforge.eventbus.EventBus$$Lambda$1475/0x000001478a704d08@6001e94e
                25: net.minecraftforge.eventbus.EventBus$$Lambda$1475/0x000001478a704d08@4b4194d8
                26: ASM: stepsword.mahoutsukai.handlers.ServerHandler@100e0892 worldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                27: ASM: class com.simibubi.create.foundation.events.CommonEvents onServerWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                28: net.minecraftforge.eventbus.EventBus$$Lambda$1475/0x000001478a704d08@1bd5d5f7
                29: ASM: wayoftime.bloodmagic.util.handler.event.WillHandler@6a90a96e onServerWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                30: ASM: class me.desht.modularrouters.event.TickEventHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                31: ASM: class com.enderio.conduits.common.network.ConduitSavedData onLevelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                32: ASM: class com.enderio.base.common.handler.FireCraftingHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                33: ASM: class com.mrh0.createaddition.event.GameEvents worldTickEvent(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                34: ASM: class com.minecolonies.coremod.event.FMLEventHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                35: ASM: class com.gregtechceu.gtceu.forge.ForgeCommonEventListener levelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                36: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@39a8934a worldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                37: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@521d8069 levelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                38: ASM: dev.shadowsoffire.apotheosis.adventure.boss.BossEvents@3d800df9 tick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                39: ASM: de.ellpeck.naturesaura.events.CommonEvents@76462b44 onLevelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                40: ASM: mcjty.xnet.setup.ForgeEventHandlers@315ecfe4 onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                41: ASM: mcjty.lostcities.setup.ForgeEventHandlers@68346eee onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                42: ASM: com.refinedmods.refinedstorage.apiimpl.network.NetworkListener@659d0514 onLevelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                43: ASM: mcjty.lib.setup.ModSetup$EventHandler@442ad621 onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                44: ASM: mcjty.deepresonance.modules.radiation.manager.RadiationTickEvent@2f32033d onTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                45: net.minecraftforge.eventbus.EventBus$$Lambda$1475/0x000001478a704d08@5a5b3db2
                46: ASM: mcjty.rftoolsbuilder.modules.scanner.ShapeHandler@650799a9 onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                47: ASM: mcjty.rftoolsutility.setup.ForgeEventHandlers@eac30cf onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                48: net.minecraftforge.eventbus.EventBus$$Lambda$1475/0x000001478a704d08@357fe42e
                49: ASM: mekanism.common.CommonWorldTickHandler@49014b57 onTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
                50: ASM: class net.silentchaos512.lib.util.EntityHelper onWorldTick(Lnet/minecraftforge/event/TickEvent;)V
                51: ASM: org.cyclops.evilcraft.core.fluid.WorldSharedTankCache@f8d252a onTick(Lnet/minecraftforge/event/TickEvent;)V
                52: ASM: org.cyclops.integrateddynamics.core.TickHandler@1712a098 onTick(Lnet/minecraftforge/event/TickEvent;)V
                53: ASM: org.cyclops.integrateddynamics.core.NoteBlockEventReceiver@1c556a1a onTick(Lnet/minecraftforge/event/TickEvent;)V
                54: ASM: me.lucko.spark.forge.ForgeTickHook@35a2f373 onTick(Lnet/minecraftforge/event/TickEvent;)V
                55: ASM: me.lucko.spark.forge.ForgeTickReporter@694eb8b onTick(Lnet/minecraftforge/event/TickEvent;)V
java.lang.NullPointerException: Cannot invoke "com.minecolonies.api.colony.IColony.getWorld()" because "colony" is null
        at TRANSFORMER/minecolonies@1.20.1-1.1.192-BETA/com.minecolonies.coremod.util.AdvancementUtils.TriggerAdvancementPlayersForColony(AdvancementUtils.java:19)
        at TRANSFORMER/minecolonies@1.20.1-1.1.192-BETA/com.minecolonies.coremod.placementhandlers.main.SurvivalHandler.handle(SurvivalHandler.java:176)
        at TRANSFORMER/structurize@1.20.1-1.0.648-BETA/com.ldtteam.structurize.storage.BlueprintPlacementHandling.process(BlueprintPlacementHandling.java:76)
        at TRANSFORMER/structurize@1.20.1-1.0.648-BETA/com.ldtteam.structurize.storage.BlueprintPlacementHandling.lambda$handlePlacement$0(BlueprintPlacementHandling.java:55)
        at TRANSFORMER/structurize@1.20.1-1.0.648-BETA/com.ldtteam.structurize.storage.ServerFutureProcessor.onWorldTick(ServerFutureProcessor.java:73)
        at TRANSFORMER/structurize@1.20.1-1.0.648-BETA/com.ldtteam.structurize.storage.__ServerFutureProcessor_onWorldTick_LevelTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/forge@47.1.3/net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:908)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:899)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
        at java.base/java.lang.Thread.run(Thread.java:833)

[19:22:44] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "com.minecolonies.api.colony.IColony.getWorld()" because "colony" is null
        at com.minecolonies.coremod.util.AdvancementUtils.TriggerAdvancementPlayersForColony(AdvancementUtils.java:19) ~[minecolonies-1.20.1-1.1.192-BETA.jar%23652!/:1.20.1-1.1.192-BETA] {re:classloading}
        at com.minecolonies.coremod.placementhandlers.main.SurvivalHandler.handle(SurvivalHandler.java:176) ~[minecolonies-1.20.1-1.1.192-BETA.jar%23652!/:1.20.1-1.1.192-BETA] {re:classloading,pl:runtimedistcleaner:A}
        at com.ldtteam.structurize.storage.BlueprintPlacementHandling.process(BlueprintPlacementHandling.java:76) ~[structurize-1.20.1-1.0.648-BETA.jar%23736!/:1.20.1-1.0.648-BETA] {re:classloading}
        at com.ldtteam.structurize.storage.BlueprintPlacementHandling.lambda$handlePlacement$0(BlueprintPlacementHandling.java:55) ~[structurize-1.20.1-1.0.648-BETA.jar%23736!/:1.20.1-1.0.648-BETA] {re:classloading}
        at com.ldtteam.structurize.storage.ServerFutureProcessor.onWorldTick(ServerFutureProcessor.java:73) ~[structurize-1.20.1-1.0.648-BETA.jar%23736!/:1.20.1-1.0.648-BETA] {re:classloading}
        at com.ldtteam.structurize.storage.__ServerFutureProcessor_onWorldTick_LevelTickEvent.invoke(.dynamic) ~[structurize-1.20.1-1.0.648-BETA.jar%23736!/:1.20.1-1.0.648-BETA] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:908) ~[forge-1.20.1-47.1.3-universal.jar%23788!/:?] {re:mixin,re:classloading,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:899) ~[server-1.20.1-20230612.114412-srg.jar%23783!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:273) ~[server-1.20.1-20230612.114412-srg.jar%23783!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[server-1.20.1-20230612.114412-srg.jar%23783!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23783!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23783!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
[19:22:45] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 5ec4e22c-c055-4c7f-b25c-71717191a65b
[19:22:45] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: C:\Users\Administrator\Desktop\Spiele\Minecraft Server\All the Mods 9 Server-Files-0.1.11\.\crash-reports\crash-2023-10-01_19.22.45-server.txt
[19:22:45] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[19:22:45] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[19:22:45] [Server thread/INFO] [minecraft/ServerGamePacketListenerImpl]: Ratnarok lost connection: Server closed
[19:22:45] [Server thread/INFO] [minecraft/MinecraftServer]: Ratnarok left the game
[19:22:45] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[19:22:49] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
java.util.concurrent.RejectedExecutionException: Server already shutting down
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_201446_(MinecraftServer.java:1279)
        at TRANSFORMER/spark@1.10.53/me.lucko.spark.forge.plugin.ForgeServerSparkPlugin.executeSync(ForgeServerSparkPlugin.java:222)
        at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782)
        at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005)
        at TRANSFORMER/spark@1.10.53/me.lucko.spark.common.platform.world.AsyncWorldInfoProvider.async(AsyncWorldInfoProvider.java:54)
        at TRANSFORMER/spark@1.10.53/me.lucko.spark.common.platform.world.AsyncWorldInfoProvider.pollCounts(AsyncWorldInfoProvider.java:76)
        at TRANSFORMER/spark@1.10.53/me.lucko.spark.common.platform.world.AsyncWorldInfoProvider.getCounts(AsyncWorldInfoProvider.java:84)
        at TRANSFORMER/spark@1.10.53/me.lucko.spark.common.sampler.window.WindowStatisticsCollector.measure(WindowStatisticsCollector.java:185)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at TRANSFORMER/spark@1.10.53/me.lucko.spark.common.sampler.window.WindowStatisticsCollector.measureNow(WindowStatisticsCollector.java:123)
        at TRANSFORMER/spark@1.10.53/me.lucko.spark.common.sampler.java.JavaSampler$InsertDataTask.run(JavaSampler.java:178)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Brother-Blue** [comment]
This is a known issue in MineColonies
https://github.com/ldtteam/minecolonies/issues/9420
