### ISSUE TITLE
forge 47.0.19 game crash Rendering Block Entity

### ISSUE THREAD

**Issue by chevr057** [AllTheMods/ATM-9#51]
game crash due to Rendering Block Entity, 
Cannot read field "id" because "b" is null
me.jellysquid.mods.sodium.client.render.vertex.serializers.VertexSerializerCache.getSerializerKey(VertexSerializerCache.java:47) ~[rubidium-0.6.5.jar%23449!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:vertex_format.MixinVertexSerializerCache,pl:mixin:A}
	at me.jellysquid.mods.sodium.client.render.vertex.serializers.VertexSerializerCache.get(VertexSerializerCache.java:36) ~[rubidium-0.6.5.jar%23449!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.compat.sodium.json:vertex_format.MixinVertexSerializerCache,pl:mixin:A}
	at com.mojang.blaze3d.vertex.BufferBuilder.copySlow(BufferBuilder.java:1089) ~[client-1.20.1-20230612.114412-srg.jar%23484!/:?]

**Comment by whatthedrunk** [comment]
We are currently on 47.0.34 try updating.
