### ISSUE TITLE
Claimed chunks crashes game

### ISSUE THREAD

**Issue by Reshuram** [AllTheMods/ATM-9#75]
I caused a CTD by having a claimed chunk prevent an enderman from picking up a block. The crash log reads thus:
java.lang.UnsupportedOperationException: Attempted to call Event#setCanceled() on a non-cancelable event of type: net.minecraftforge.event.entity.EntityMobGriefingEvent
	at net.minecraftforge.eventbus.api.Event.setCanceled(Event.java:92) ~[eventbus-6.0.5.jar%2387!/:?] {re:mixin}
	at dev.ftb.mods.ftbchunks.forge.FTBChunksForge.mobGriefing(FTBChunksForge.java:62) ~[ftb-chunks-forge-2001.1.2.jar%23457!/:2001.1.2] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.getMobGriefingEvent(ForgeEventFactory.java:715) ~[forge-1.20.1-47.0.43-universal.jar%23595!/:?] {re:classloading}
	at net.minecraft.world.entity.monster.EnderMan$EndermanTakeBlockGoal.m_8036_(EnderMan.java:556) ~[client-1.20.1-20230612.114412-srg.jar%23590!/:?] {re:classloading}
The entire log will be provided for posterity.
[crash-2023-07-08_14.01.04-server.txt](https://github.com/AllTheMods/ATM-9/files/11990630/crash-2023-07-08_14.01.04-server.txt)

**Comment by Mitchell5200** [comment]
roll back to .26 of the pack, .27 was removed from CF after we found the crash
