### ISSUE TITLE
ATM9 - Server crashes when opening certain lootr chests

### ISSUE THREAD

**Issue by NoahGBaker** [AllTheMods/ATM-9#76]
I've noticed that whenever I open lootr chests specifically ones like the desert temple and ruined portal chests chrash my game. I belive its specifically Minecraft loot tables are the problem, modded ones that are perfectly fine. The crash report says its a problem with Pnematicraft and IronSpells. I think they are modifying the loot tables and crashing the server. Another thing this crash doesn't happen on singleplayer worlds.

Here is the message it gave me before the crash: 
I hope the atm team can fix this and ty
java.lang.StackOverflowErrornull
[08.07 12:49:31] [Server] 	at java.util.stream.SpinedBuffer.ensureCapacity(SpinedBuffer.java:133) ~[?:?] {}
[08.07 12:49:31] [Server] 	at java.util.stream.SpinedBuffer.increaseCapacity(SpinedBuffer.java:154) ~[?:?] {}
[08.07 12:49:31] [Server] 	at java.util.stream.SpinedBuffer.accept(SpinedBuffer.java:258) ~[?:?] {}
[08.07 12:49:31] [Server] 	at java.util.stream.Nodes$SpinedNodeBuilder.accept(Nodes.java:1277) ~[?:?] {}
[08.07 12:49:31] [Server] 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
[08.07 12:49:31] [Server] 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}
[08.07 12:49:31] [Server] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
[08.07 12:49:31] [Server] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
[08.07 12:49:31] [Server] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?] {}
[08.07 12:49:31] [Server] 	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?] {}
[08.07 12:49:31] [Server] 	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?] {}
[08.07 12:49:31] [Server] 	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?] {}
[08.07 12:49:31] [Server] 	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?] {}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.SpellFilter.getApplicableSpells(SpellFilter.java:42) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.RandomizeSpellFunction.m_7372_(RandomizeSpellFunction.java:40) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction.apply(LootItemConditionalFunction.java:31) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,re:classloading}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.RandomizeSpellFunction.apply(RandomizeSpellFunction.java:24) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemFunction.m_80728_(LootItemFunction.java:14) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootItem.m_6948_(LootItem.java:33) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$1.m_6941_(LootPoolSingletonContainer.java:59) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootPool.m_79058_(LootPool.java:79) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:croptopia.mixins.json:LootPoolAccessor,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootPool.m_79053_(LootPool.java:94) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:croptopia.mixins.json:LootPoolAccessor,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79131_(LootTable.java:85) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:117) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_230922_(LootTable.java:118) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:104) ~[server-1.20.1-20230612.114412-srg.jar%23529!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
[08.07 12:49:31] [Server] 	at io.redspace.ironsspellbooks.loot.AppendLootModifier.doApply(AppendLootModifier.java:36) ~[irons_spellbooks-1.20.1-1.1.6.2.jar%23418!/:1.20.1-1.1.6.{re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:58) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:31] [Server] 	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1163) ~[forge-1.20.1-47.0.50-universal.jar%23534!/:?] {re:classloading}
[08.07 12:49:32] [Multicraft] Skipped 934 lines due to rate limit (100/s)
[08.07 12:49:32] [Server] java.util.concurrent.RejectedExecutionExceptionServer already shutting down

**Comment by zombiebush** [comment]
This same thing happend to me and im a singleplayer 
[crash-2023-07-09_11.33.26-server.txt](https://github.com/AllTheMods/ATM-9/files/11995902/crash-2023-07-09_11.33.26-server.txt)

**Comment by whatthedrunk** [comment]
https://github.com/AllTheMods/ATM-9/issues/80

**Comment by whatthedrunk** [comment]
still happening on 0.0.32? I cant seem to get myself to crash

**Comment by alcemr** [comment]
> 

i update my server and it got fix
