### ISSUE TITLE
ATM 9 - 0.2.15 -  Crashes when placing townhall for mine colonies

### ISSUE THREAD

**Issue by Drelok** [AllTheMods/ATM-9#768]
Started a brand new install and world with the release of .15 today.   Placing a townhall in mine colonies (using Caverns style, not sure that matters) crashes the game with the following error.    .14 has structurize 1.0.659, replacing the newer version in .15 (1.0.662) with this file from .14 fixed the crash.  As far as I can tell this is the only file that was changed in regards to mine colonies from 0.2.14 to 0.2.15

[10:34:08] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.world.level.block.state.BlockState com.ldtteam.structurize.blueprints.v1.Blueprint.getBlockState(net.minecraft.core.BlockPos)'
	at com.minecolonies.coremod.placementhandlers.main.SurvivalHandler.handle(SurvivalHandler.java:109) ~[minecolonies-1.20.1-1.1.303-BETA.jar%23743!/:1.20.1-1.1.303-BETA] {re:classloading}
	at com.ldtteam.structurize.storage.BlueprintPlacementHandling.process(BlueprintPlacementHandling.java:76) ~[structurize-1.20.1-1.0.662-BETA.jar%23841!/:1.20.1-1.0.662-BETA] {re:classloading}
	at com.ldtteam.structurize.storage.BlueprintPlacementHandling.lambda$handlePlacement$0(BlueprintPlacementHandling.java:55) ~[structurize-1.20.1-1.0.662-BETA.jar%23841!/:1.20.1-1.0.662-BETA] {re:classloading}
	at com.ldtteam.structurize.storage.ServerFutureProcessor.onWorldTick(ServerFutureProcessor.java:73) ~[structurize-1.20.1-1.0.662-BETA.jar%23841!/:1.20.1-1.0.662-BETA] {re:classloading}
	at com.ldtteam.structurize.storage.__ServerFutureProcessor_onWorldTick_LevelTickEvent.invoke(.dynamic) ~[structurize-1.20.1-1.0.662-BETA.jar%23841!/:1.20.1-1.0.662-BETA] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostLevelTick(ForgeEventFactory.java:908) ~[forge-1.20.1-47.1.3-universal.jar%23901!/:?] {re:mixin,re:classloading,pl:mixin:APP:aether.mixins.json:common.ForgeEventFactoryMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:899) ~[client-1.20.1-20230612.114412-srg.jar%23896!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23896!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23896!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23896!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23896!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
[10:34:08] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 81ebb801-a1b6-4807-b0dc-814b6b1e9f81
[10:34:08] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: G:\MC\MultiMC\instances\ATM 9 - 0.2.15\.minecraft\crash-reports\crash-2023-11-10_10.34.08-server.txt

**Comment by AlisAquilae** [comment]
I am having many issues as well, having updated my existig world into 0.2.15. No minecolonies blocks can be placed anymore and build orders cannot be started or resumed. Doing either of those things will result in an immediate crash

**Comment by DerTyp7** [comment]
Same issue. But this comes when a Builder in your town accepts a new job. Crashes the server every time.
Minecolonies also has an issue open on their GitHub since today: https://github.com/ldtteam/minecolonies/issues/9561.

If you want at least prevent the server from crashing, you could go into this folder in your server "world/serverconfig/forge-server.toml" and set `removeErroringBlockEntities` and `removeErroringEntities` to `true`.
This lets your Builder respawn every time they "crash" instead of crashing the hole server.
I did this and canceled all buildings which are in progress.

It's obviously only temporary and makes your builders unusable, but at least the hole server isn't crashing

**Comment by Drelok** [comment]
Does reverting back to Structurize 1.0.659 fix those issues as well?   It fixed the placing the block, and it seems the other functions are working, but just getting started so only have placed and had them start the builders hut

**Comment by NHendley** [comment]
Thank you all for the recommendations. Cancelled all my build requests but still crashing.

Hopefully folks that know more than I do help get this fixed, but glad to see it is acknowledged and my world isn't forever lost

Time: 2023-11-10 15:51:54
Description: Ticking entity
-- Entity being ticked --
Details:
	Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.citizen.EntityCitizen)
	Entity ID: 1550
	Entity Name: Emory O. Bammard
	Entity's Exact location: 2701.52, 72.00, 467.42
	Entity's Block location: World: (2701,72,467), Section: (at 13,8,3 in 168,4,29; chunk contains blocks 2688,-64,464 to 2703,319,479), Region: (5,0; contains chunks 160,0 to 191,31, blocks 2560,-64,0 to 3071,319,511)
	Entity's Momentum: 0.10, -0.08, 0.01
	Entity's Passengers: []
	Entity's Vehicle: null

**Comment by aAndrew3030** [comment]
This has been fixed in the latest version of Minecolonies
