### ISSUE TITLE
Error receiving packet 109 java.lang.IllegalArgumentException: Packet too big (is 18480481, should be less than 8388608)

### ISSUE THREAD

**Issue by eloo-dev** [AllTheMods/ATM-9#848]
Is this a mistake from the modpack or am I just too stupid to see what exactly is happening here or what is causing this error? 

[14:24:15] [Netty Epoll Server IO #1/ERROR] [net.minecraft.network.PacketEncoder]: Error receiving packet 109
java.lang.IllegalArgumentException: Packet too big (is 18480481, should be less than 8388608): net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket@64c51467
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:48) ~[server-1.20.1-20230612.114412-srg.jar%23926!/:?]
	at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:14) ~[server-1.20.1-20230612.114412-srg.jar%23926!/:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.82.Final.jar%23167!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.82.Final.jar%23167!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.82.Final.jar%23167!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.82.Final.jar%23171!/:4.1.82.Final]
	at net.minecraft.network.Connection.m_243087_(Connection.java:232) ~[server-1.20.1-20230612.114412-srg.jar%23926!/:?]
	at net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:221) ~[server-1.20.1-20230612.114412-srg.jar%23926!/:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.82.Final.jar%23168!/:4.1.82.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.82.Final.jar%23168!/:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.82.Final.jar%23168!/:4.1.82.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) [netty-transport-classes-epoll-4.1.82.Final.jar%23172!/:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.82.Final.jar%23168!/:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.82.Final.jar%23168!/:4.1.82.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[14:24:15] [Netty Epoll Server IO #1/DEBUG] [mixin]: Mixing access.StructuresAccess from enhancedcelestials.mixins.json into net.minecraft.data.worldgen.Structures
[14:24:15] [Netty Epoll Server IO #1/DEBUG] [mixin]: Renaming @Invoker method structure(Lnet/minecraft/core/HolderSet;Ljava/util/Map;Lnet/minecraft/world/level/levelgen/GenerationStep$Decoration;Lnet/minecraft/world/level/levelgen/structure/TerrainAdjustment;)Lnet/minecraft/world/level/levelgen/structure/Structure$StructureSettings; to structure_$md$17dcce$0 in enhancedcelestials.mixins.json:access.StructuresAccess
[14:24:15] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl]: **** lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Packet too big (is 18480481, should be less than 8388608): net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket@64c51467
[14:24:15] [Netty Epoll Server IO #1/DEBUG] [mixin]: Mixing RegistrySetBuilderMixin from lost_aether_content.mixins.json into net.minecraft.core.RegistrySetBuilder$BuildState
[14:24:15] [Netty Epoll Server IO #1/DEBUG] [mixin]: Renaming synthetic method lambda$throwOnError$0(Ljava/lang/RuntimeException;)V to md17dcce$lambda$throwOnError$0$0 in lost_aether_content.mixins.json:RegistrySetBuilderMixin

**Comment by MBlan18** [comment]
Try adding PacketFixer to either your client or server.
